apiVersion: v1
kind: Service
metadata:
  name: account-service-command
spec:
  selector:
    app: account-service
    profile: command
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
