name: CI/CD workflow for config-service

on:
  push:
    branches:
      - release-1
    paths:
      - 'config-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'config-service/**'

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/ckeckout@v5
      - name: Set up Java 17
        uses: actions/setup-java@vp
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -B --file config-service/pom.xml
  dockerize:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t ghcr.io/kopyn/cqrs-project/config-service:latest ./config-service
      - name: Push docker image to ghcr
        run: docker push ghcr.io/kopyn/cqrs-project/config-service:latest
