name: CI/CD workflow for registry-service

on: 
  push:
    branches:
      - release-1
    paths:
      - 'registry-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'registry-service/**'

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Maven clean package
        run: mvn -B clean package --file registry-service/pom.xml
  dockerize:
    runs-on: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build docker image
        run: docker build -t  ghcr.io/kopyn/cqrs-project/registry-service:latest ./registry-service
      - name: Push docker image to the registry
        run: docker push  ghcr.io/kopyn/cqrs-project/registry-service:latest
