name: CI/CD workflow for transaction-history-service

on:
  push:
    branches:
      - release-1
    paths:
      - 'transaction-history-service/**'
  pull_request:
    branches:
      - main
    paths:
      - 'transaction-history-service/**'

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
  dockerize:
    runs-on: ubuntu:latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v5
